---
label: Test
hide_body: false
fields:
- name: test-name
  type: text
  config:
    required: false
  label: test-label
  description: This is my test page
pages:
- config/_default/content/test-file-name.md
